services:
  api:
    container_name: api_apocachef
    build: ./api
    volumes:
      - ./api:/var/www/html
      - ./framework:/var/www/framework
      - ./env:/var/www/env
    ports:
      - "5000:80"
    env_file:
      - env/.env
    depends_on:
      - db

  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/var/www/html
      - ./framework:/var/www/framework
      - ./env:/var/www/env
    ports:
      - "3000:80"
    env_file:
      - env/.env
    depends_on:
      - api

  db:
    container_name: db
    build: ./api/database
    environment:
      POSTGRES_DB: receitas_apocalipticas
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./api/database/backups:/api/database/backups
    ports:
      - "5432:5432"

volumes:
  pgdata: